# 端口号
server:
  port: 8081
  servlet:
    context-path: /mark
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  application:
    name: mark
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: db01, db02
      db01:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.117:3306/benz?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 123456
      db02:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.117:3306/benz_02?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 123456
    sharding:
      tables:
        t_order:
          actualDataNodes: db01.t_order_$‐>{0..7}
          tableStrategy:
            inline:
              shardingColumn: order_id
              algorithmExpression: t_order_$‐>{order_id % 8}
          keyGenerator:
            type: SNOWFLAKE
            column: order_id
    props:
      sql:
        show: true



# 连接 MySQL 数据库
# spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver #驱动注释,采用默认的方式
#    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#    username: root
#    password: root
# (1)、时区，数据库驱动的高版本需要使用时区操作 serverTimezone=GMT%2B8 %2B +
# (2)、使用 useUnicode=true 编码
# (3)、characterEncoding=utf8 字符采用utf-8编码
# (4)、autoReconnect=true 如果mysql链接断掉之后是否重连
# (5)、allowMultiQueries=true 是否允许批量操作
#  mysql -h192.168.0.112 -uroot -p123456 -A
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.117:3306/benz?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#
#  # sharding-jdbc 分片配置
#  # 定义数据源
#  shardingsphere:
#    datasource:
#      names: datasource01
#      datasource01:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://192.168.0.117:3306/benz?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#        username: root
#        password: 123456
#    # 路由规则
#    sharding:
#      tables:
#        tb_order:
#          # 指定 tb_order 表的数据分布情况，配置数据节点: datasource01.tb_order_1、datasource01.tb_order_2
#          actual-data-nodes: datasource01.tb_order_$->{1..8}
#          # 指定 tb_order 表的主键生成策略为 snowflake
#          key-generator:
#            column: order_id
#            type: SNOWFLAKE
#          # 指定 tb_order 表的分片策略，分片策略包括分片键和分片算法
#          table-strategy:
#            inline:
#              sharding-column: order_id
#              algorithm-expression: t_order_$->{order_id % 8 +1 }
#    # 打开 SQL 输出日志
#    props:
#      sql:
#        show: true


mybatis:
  mapper-locations: classpath:*mapper/*.xml
  config-location:
    map‐underscore‐to‐camel‐case: true

